//
// Created by USER on 23/01/2024.
//

#ifndef STUDYING_DATA_STRUCTURES_ARRAY_PRACTICE_H
#define STUDYING_DATA_STRUCTURES_ARRAY_PRACTICE_H

void resize_array();
void creating_2D_arrays();

#endif //STUDYING_DATA_STRUCTURES_ARRAY_PRACTICE_H
